# Site settings
title: mas865.15 notes
email: weller@mit.edu
author: Tomer Weller
description: "How to Make Something that Makes (almost) Anything class notes by Tomer Weller "
baseurl: "/classes/865.15/people/tomer.weller"
url: "http://fab.cba.mit.edu"
google_analytics: 
animated: false
show_related_posts: false


# Build settings
markdown: kramdown
permalink: pretty
paginate: 20
sass:
  compressed: true